[package]
name = "open_track"
version = "0.1.0"
authors = ["Christoph Schr√∂der <cs@keksdev.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
